#   业务配置-------------------------------------------------------------








#   服务配置-------------------------------------------------------------
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 20MB  # 设置单个文件的最大大小 (例如：20MB)
      max-request-size: 20MB  # 设置总请求的最大大小 (例如：20MB)

server:
  port: 8999
  http2:
    enabled: true
  servlet:
    context-path: /shareaccount
  #ssl:
  #  key-store: classpath:keystore.jks # 证书路径
  #  key-store-password: changeit       # 证书密码
  #  key-password: changeit             # 密钥密码（如果需要）


logging:
  level:
    com.github.pagehelper: DEBUG
    cn.lizongyi.shareaccount.dao: DEBUG
    org:
      springframework:
        jdbc:
          datasource: debug


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    # 打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰命名规则转换
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

